platformURL: 'http://localhost:5173'

accessToken:
  secret: accessTokenSECRET123
  ttl: 600

refreshToken:
  secret: refreshTokenSECRET123
  ttl: 172800

ses:
  endpoint: 'http://mockserver'

notificationsEmailAddress: notifications@ludi.com
