apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ludi-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: PGHOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: host
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: database
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: url

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 30007
